CREATE DATABASE in_home_restaurant WITH CONNECTION LIMIT = 128;
GO;

USE in_home_restaurant;
GO;

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(64) NOT NULL UNIQUE,
	email VARCHAR(128) NOT NULL UNIQUE,
	passwordhash VARCHAR(255) NOT NULL,
	role VARCHAR(32) NOT NULL DEFAULT 'user'
);
GO;

CREATE TABLE prices (
	id SERIAL PRIMARY KEY,
	name VARCHAR(64) NOT NULL UNIQUE
);
GO;

CREATE TABLE price_matches (
	id SERIAL PRIMARY KEY,
	price_id INTEGER NOT NULL REFERENCES prices(id) ON DELETE CASCADE ON UPDATE CASCADE,
	product_id BIGINT NOT NULL,
	url VARCHAR(255) NOT NULL,
	store VARCHAR(64) NOT NULL
);

SELECT * FROM prices;